# 기본 질의(QUERY)

# 릴레이션의 모든 애트리뷰트, 일부 애트리뷰트 검색하는 질의

# 전체부서의 모든 애트리뷰트를 검색하라.
SELECT DEPTNO, DEPTNAME, FLOOR
FROM DEPARTMENT;

SELECT *
FROM DEPARTMENT;
# 모든 사원의 모든 정보를 검색하라.
SELECT *
FROM EMPLOYEE;

# 모든 부서의 부서번호와 이름을 검색하라.
SELECT DEPTNO, DEPTNAME
FROM DEPARTMENT;

# 모든사원의 직급을 검색하라.
SELECT TITLE
FROM EMPLOYEE;

# 모든 사원들의 상이한 직급을 검색하라.
SELECT DISTINCT TITLE
FROM EMPLOYEE;

#  2번 부서에 근무하는 사원에 대한 모든 정보를 검색하라.
SELECT *
FROM EMPLOYEE
WHERE DNO=2;

#  '조민희'사원에 대한 모든 정보를 검색하라.
SELECT *
FROM EMPLOYEE
WHERE EMPNAME='조민희';

#  이씨 성을 가진 사원들의 이름, 직급, 소속부서번호를 검색하라.
SELECT EMPNAME, TITLE, DNO
FROM EMPLOYEE
WHERE EMPNAME LIKE '이%';

# 이름에 '민'이 포함된 사원의 이름, 직급을 검색하라.
SELECT EMPNAME, TITLE
FROM EMPLOYEE
WHERE EMPNAME LIKE '%민%';

SELECT *
FROM EMPLOYEE
WHERE EMPNAME LIKE '이__';
# 직급이 과장이면서 1번 부서에 근무하는 사원의 이름과 급여를 검색하라.
SELECT EMPNAME, SALARY
FROM EMPLOYEE
WHERE TITLE='과장' AND DNO='1';

SELECT EMPNAME, SALARY
FROM EMPLOYEE
WHERE TITLE='과장' AND DNO != '1';

# 범위(RANGE)를 사용한 검색
# 급여가 3000000이상, 4500000이하인 사원들의 이름과 직급, 급여를 검색해라.
SELECT EMPNAME, TITLE, SALARY
FROM EMPLOYEE
WHERE SALARY >= 3000000 AND SALARY <=4500000;

SELECT EMPNAME, TITLE, SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 3000000 AND 4500000;

# 1번 부서나 3번 부서에 소속된 사원들에 관한 모든 정보를 검색하라.
SELECT *
FROM EMPLOYEE
WHERE DNO IN (1,3);

SELECT *
FROM EMPLOYEE
WHERE DNO = 1 OR DNO = 3 OR DNO =4;

SELECT EMPNAME, SALARY
FROM EMPLOYEE
WHERE TITLE = '과장';


SELECT EMPNAME, SALARY, SALARY *1.1
FROM EMPLOYEE
WHERE TITLE = '과장';


SELECT EMPNAME ||' '||TITLE, SALARY, SALARY *1.1 AS NEWSALARY
FROM EMPLOYEE
WHERE TITLE = '과장';

-- 집단 함수의 사용 : AVG, MAX, MIN, SUM
SELECT AVG(SALARY) AS AVGSAL, MAX(SALARY) AS MAXSAL
FROM EMPLOYEE;

# 널 값의 비교
SELECT *
FROM EMPLOYEE;

# 상사가 없는 사원의 모든 정보를 검색하라.
SELECT *
FROM EMPLOYEE
WHERE MANAGER IS NULL;